# Generated by Django 4.2.6 on 2023-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='имя')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='new_app/', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='new_app/', verbose_name='превью')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
