# Generated by Django 4.2.6 on 2023-10-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_lesson_course_alter_payment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='превью'),
        ),
    ]
