# Generated by Django 4.2.6 on 2023-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_subscription_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sum_of_payment',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=1, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
