# Generated by Django 4.2.6 on 2023-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_rename_sum_of_payment_payment_amount_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Безналичные', 'Безналичные')], default='CARD', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
