# Generated by Django 4.2.6 on 2023-10-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='town',
            new_name='country',
        ),
    ]
