# Generated by Django 4.2.6 on 2023-10-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_town_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='town',
        ),
    ]
